# Generated by Django 3.2.4 on 2021-08-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_auto_20210607_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
